### ISSUE TITLE
Legacy Illumina FASTQ Header Parsing

### ISSUE THREAD

**Issue by mossmatters** [mossmatters/HybPiper#13]
With the Cassava 1.8 chemistry, Illumina changed the way the headers are generated for FASTQ files:

https://en.wikipedia.org/wiki/FASTQ_format

When parsing reads, both BWA and BLAST take only the first part of the header, until the first whitespace character. Using the more recent Illumina format:

`@EAS139:136:FC706VJ:2:2104:15343:197393 1:Y:18:ATCACG`

Appears in the BAM files as:

`@EAS139:136:FC706VJ:2:2104:15343:197393`

The read pairing data is thus lost. However, this is fine in HybPiper because the reads are also parsed in the same way in `distribute_reads.py` and `distribute_reads_bwa.py`

However, the previous Solexa FASTQ format breaks the distribution scripts:

`@HWUSI-EAS100R:6:73:941:1973#0/1`

Is listed as `@HWUSI-EAS100R:6:73:941:1973#0` in the BAM output. The read distribution scripts therefore never identify any reads, resulting in the following HybPiper error:

`ERROR: No genes with BLAST hits! Exiting!`

**Comment by mossmatters** [comment]
Adding a check for whether the FASTQ ids end with `/1` or `/2` in `distribute_reads_to_bwa.py`

**Comment by iamcorrinne** [comment]
I have run into this error.  AFAIK, the IT department packaged the newest version of HybPiper just a week or so ago.  Do you have an updated version of distribute_reads_to_bwa.py to compensate for this? I'd like to avoid hacking the headers to make it work.  Otherwise, the pipeline is working very well for us.

Thanks!

**Comment by mossmatters** [comment]
I have fixed this on the development branch (commit: https://github.com/mossmatters/HybPiper/commit/15b82ce027917246df00d9f43188b94646985416) 

I am planning a few more bug fixes/feature additions this week, so until then you can grab the updated `distribute_reads_to_targets_bwa.py` from here and replace it in your HybPiper directory:

https://github.com/mossmatters/HybPiper/blob/develop/distribute_reads_to_targets_bwa.py

**Comment by iamcorrinne** [comment]
Awesome, thanks!

**Comment by hk20013106** [comment]
Hi Matt,

I'm just running the test_dataset, and I'm still getting this problem when using the latest version. 

First, I check the dependencies. 

----------
./reads_first.py --check-dependHybPiper was called with these arguments:
./reads_first.py --check-depend

blastx found at /home/hk20013106/miniconda2/bin/blastx
exonerate found at /home/hk20013106/.linuxbrew/bin/exonerate
parallel found at /home/hk20013106/.linuxbrew/bin/parallel
makeblastdb found at /home/hk20013106/miniconda2/bin/makeblastdb
spades.py found at /home/hk20013106/miniconda2/bin/spades.py
bwa found at /home/hk20013106/miniconda2/bin/bwa
samtools found at /home/hk20013106/miniconda2/bin/samtools
Package Bio successfully loaded!
Everything looks good!

----------

Then I run the run_test.sh 

----------

HybPiper was called with these arguments:
../reads_first.py -r NZ911*.fastq -b test_targets.fasta --prefix NZ911 --bwa

Making nucleotide bwa index in current directory.
[CMD]: bwa index test_targets.fasta
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.01 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.7-r441
[main] CMD: bwa index test_targets.fasta
[main] Real time: 0.022 sec; CPU: 0.012 sec
[CMD]: time bwa mem -t 2 test_targets.fasta /home/hk20013106/Tools/HybPiper/test_dataset/NZ911*.fastq  | samtools view -h -b -S - >  NZ911.bam
[M::main_mem] read 22548 sequences (4986549 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 3844, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (339, 444, 539)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 939)
[M::mem_pestat] mean and std.dev: (438.57, 143.49)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1139)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 22548 reads in 6.276 CPU sec, 3.538 real sec
[samopen] SAM header is present: 26 sequences.
[main] Version: 0.7.7-r441
[main] CMD: bwa mem -t 2 test_targets.fasta /home/hk20013106/Tools/HybPiper/test_dataset/NZ911_R1_test.fastq /home/hk20013106/Tools/HybPiper/test_dataset/NZ911_R2_test.fastq
[main] Real time: 4.445 sec; CPU: 6.336 sec
5.63user 0.70system 0:04.44elapsed 142%CPU (0avgtext+0avgdata 36000maxresident)k
0inputs+0outputs (0major+8425minor)pagefaults 0swaps
[CMD] time python /home/hk20013106/Tools/HybPiper/distribute_reads_to_targets_bwa.py NZ911.bam /home/hk20013106/Tools/HybPiper/test_dataset/NZ911*.fastq

Unique reads with hits: 7744
0.65user 0.24system 0:00.96elapsed 92%CPU (0avgtext+0avgdata 28244maxresident)k
0inputs+8200outputs (0major+8008minor)pagefaults 0swaps
/home/hk20013106/miniconda2/envs/biopython/lib/python2.7/site-packages/Bio/Seq.py:2071: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
[DISTRIBUTE]: 0 proteins had no good matches.
0.28user 0.06system 0:00.37elapsed 94%CPU (0avgtext+0avgdata 26292maxresident)k
0inputs+112outputs (0major+7643minor)pagefaults 0swaps
ERROR: No genes with BLAST hits! Exiting!
----------

I have no idea what is happening here. 
It will be really appreciated if you can take a quick a look and provide any comments. 

Thanks a lot!

Kai HE

**Comment by cp-weiland** [comment]
Try to uncomment "$i..."
< ../reads_first.py -r $i*.fastq -b test_targets.fasta --prefix $i --bwa 
---
> ../reads_first.py -r "$i*.fastq" -b test_targets.fasta --prefix $i --bwa

**Comment by coyotree** [comment]
Hi Matt,

I am currently working with some older Illumina data with FASTQ files that start with:
@HWUSI-EAS558R_0001:7:1:1:251#0/1

I have been getting similar outputs for every file that say:
...
ERROR: No genes with BLAST hits! Exiting!
Unique reads with hits: 8
[DISTRIBUTE]: 29 proteins had no good matches.
...

I tried a simple test of making a target file with sequences from the genome skim data and then ran HybPiper using them as targets, only to receive the same output message.

Every target loci gets a folder within a taxon folder but within some of the target loci folders (not all) there is only one file (i.e. $name_baits.fasta). 

I am running HybPiper on the U of Florida SLURM system.

Please help save my PhD. ;-)

Thank you,
Cody Coyotee

**Comment by mossmatters** [comment]
Cody,

The `distribute_reads.py` script is looking for reads that match the results in the .BAM or .BLASTX file produced by either BWA or BLAST. The fix I wrote should be detecting 

Can you verify that the `distribute_reads.py` (if you are using BLASTX) or `distribute_reads_bwa.py` on UF's cluster is similar to the one linked in this issue thread? It's possible you're still using the version with the bug still in it.

If the UF version has been updated, can you send me a snippet of what the BAM or BLASTX file looks like? If it's the same problem as above, the reads should be listed as `@HWUSI-EAS558R_0001:7:1:1:251#0` in the output.

**Comment by coyotree** [comment]
Hi Matt,

Nice chatting with you at Botany earlier this week. 

I removed the \1 from all files using a sed command and it made it to the SPADES part of the program.

Now I am attempting to run HybPiper using your suggestion of telling the script that my reads are 'single-end'. However, the use of --single or --s results in an error that says "reads_first.py: error: unrecognized arguments: --single". Perhaps I am calling the wrong command.

My command is here:
python HybPiper/reads_first.py -r scill_gss_combined/${forward} -b MM_probes_no_dashes.fa --single --cpu 10 --bwa --prefix ${name}

I am using the most recent version of HybPiper downloaded from github.

Thanks,
Cody

**Comment by mossmatters** [comment]
Ah, yes I was conflating two different features:

If you only supply one read file to `reads_first.py` it should be able to assemble with no additional options. The reads should be distributed to the gene directories into a file such as `geneName/geneName_unpaired.fasta`

If there are reads in there but no contigs were made, you may consider lowering the minimum depth of coverage threshold. The default is 8, you could lower it for example with `--cov_cutoff 4`. Hopefully that should get you a few more sequences!

I had this confused with `--unpaired` in which you can supply both a set of paired read files plus a file with unpaired reads.

**Comment by coyotree** [comment]
Ok! Thanks for the information. The older data I'm using might just be insufficient for these purposes. Thanks for all of your help!
